config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :appointments, only: [:index]
  end

  resources :contacts do
    resources :appointments, only: [:index]
  end

  resources :appointments
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'welcome#home'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/list', to: 'appointments#list'
  get '/contacts/:id/get', to: 'contacts#get'
  get '/locations/:id/getAppointmentData', to: 'locations#getAppointmentData'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  include Appointable
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :phone_number, presence: true, format: { with: /\A\d{3}-\d{3}-\d{4}\z/ }

  belongs_to :user
  has_many :appointments
  has_many :locations, through: :appointments

  scope :search, lambda {|search| where(["name LIKE ?", "%#{search}%"])}

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contacts
    if !params[:contact].blank?
      @contacts = current_user.contacts.search(params[:contact])
    end
    respond_to do |format|
      format.html {}
      format.json { render json: @contacts }
    end
  end

  def new
    @contact = current_user.contacts.build
  end

  def create
    @contact = Contact.new(contact_params.merge(user_id: current_user.id)) #instantiate a contact associated with current_user, but unsaved.
    if @contact.save
      respond_to do |format|
        format.html { redirect_to contact_path(@contact)}
        format.json { render json: @contact }
      end
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to contact_path(@contact)
    else
      render :edit #add field with errors here
    end
  end

  def destroy
    @contact.delete
    flash[:notice] = "Successfully deleted contact."
    redirect_to contacts_path
  end

  def get
    respond_to do |f|
      f.json { render json: current_user.contacts.find_by_id(params[:id]) }
    end
  end

  private
  def set_contact
    @contact = current_user.contacts.find_by(id: params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :phone_number)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper

  def has_complete_fields?(contact)
    contact && contact.name && contact.email && contact.phone_number
  end

  def only_has_name_field?(contact)
    contact 
  end

end

app/views/contacts/_contact.html.erb
<div class="boxed">
<fieldset>
  <legend><%= contact.name %></legend>
</fieldset>

  <p><strong>Email: </strong><%= contact.email %></p>
  <p><strong>Phone Number: </strong><%= contact.phone_number %></p>

  <% if contact.appointments.any? %>
  <p><a href="#" class="showApptLink" id="show<%=contact.id%>" data-thisId="<%=contact.id%>">Click to view upcoming appointments with this Contact.</a></p>
  <ul id="contact<%=contact.id%>Appts"></ul>
  <% end %>

  <fieldset><legend></legend></fieldset>

  <p><%= link_to "Edit", edit_contact_path(contact) %> |
     <%= link_to "Delete", contact_path(contact), method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %> |
     <%= link_to "Back", contacts_path %>
   </p>

</div>

app/views/contacts/_form.html.erb
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h4>There were some errors:</h4>
    <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<%end%>

<%= form_for contact do |f| %>
<table>
  <tr>
    <td><%= f.label :name %></td>
    <td class="left"><%= f.text_field :name %> </td>
  </tr>

    <tr>
      <td><%= f.label :email %></td>
      <td class="left"><%= f.text_field :email %> </td>
    </tr>

  <tr>
    <td><%= f.label :phone_number, "Phone" %></td>
    <td class="left"><%= f.text_field :phone_number %> </td>
  </tr>
  <tr> <td></td>
    <td class="left"><%= f.submit %></td>
  </tr>
  </table>
<% end %>

app/views/contacts/edit.html.erb
<fieldset>
  <legend>Edit <%= @contact.name %></legend>
</fieldset>

<%= render partial: 'form', locals: {contact: @contact}%>

app/views/contacts/index.html.erb
<fieldset>
  <legend>Contacts Index</legend>
</fieldset>

<div>
  <h4>Search By Name:</h4>
  <%= form_tag("/contacts", method: :get) do %>
    <%= text_field_tag "contact" %>
    <%= submit_tag "Search" %>
    <% end %>
  </div> <br />

<%= render(@contacts) || "You haven't saved any contacts yet!" %>

<div class="hidden" id="hiddenContactField">
  <div class="boxed">
    <fieldset>
      <legend>New Contact</legend>
    </fieldset>
    <%= form_for Contact.new, html: {id: "newContactForm"}  do |f| %>
    <table>
      <tr>
        <td><%= f.label :name %></td>
        <td class="left"><%= f.text_field :name %> </td>
      </tr>

        <tr>
          <td><%= f.label :email %></td>
          <td class="left"><%= f.text_field :email %> </td>
        </tr>

      <tr>
        <td><%= f.label :phone_number, "Phone" %></td>
        <td class="left"><%= f.text_field :phone_number %> </td>
      </tr>
      <tr> <td></td>
        <td class="left"><%= f.submit %></td>
      </tr>
      </table>
      <% end %>
    </div>
  </div><br />

&nbsp &nbsp &nbsp
<button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onclick="showContactForm()">
  Create New Contact
</button>

app/views/contacts/new.html.erb
<fieldset>
  <legend>New Contact</legend>
</fieldset>

<%= render partial: 'form', locals: {contact: @contact}%>

app/views/contacts/show.html.erb
<% if @contact %>
<%= render partial: 'contact', locals: {contact: @contact} %>
<% else %>
No such contact was found!
<% end %> <br />


 &nbsp &nbsp &nbsp
 <button type="button" id="next_contact" data-nextUrl="/contacts/<%= @contact.id.to_i + 1 %>/get" class="btn btn-primary" aria-pressed="false" autocomplete="off" onclick="nextContact()">
    Next
  </button>