config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :appointments, only: [:index]
  end

  resources :contacts do
    resources :appointments, only: [:index]
  end

  resources :appointments
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'welcome#home'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/list', to: 'appointments#list'
  get '/contacts/:id/get', to: 'contacts#get'
  get '/locations/:id/getAppointmentData', to: 'locations#getAppointmentData'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  # validates :contact_id, presence: true
  # validates :location_id, presence: true
  validates_associated :contact
  validates_associated :location
  # accepts_nested_attributes_for :location

  belongs_to :user
  belongs_to :contact
  belongs_to :location
  scope :search, lambda {|search| where(["name LIKE ?", "%#{search}%"])}


  def contact_attributes=(contact_attr)
    if contact_attr[:name].present?
      self.contact = self.user.contacts.find_or_create_by(contact_attr)
    end
  end

  def location_attributes=(location_attr)
    if location_attr[:name].present?
      self.location = self.user.locations.find_or_create_by(location_attr)
    end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_appointments, only: [:index, :new, :edit]
  before_action :evaluate_params, only: [:index]

  def index
  end

  def new
    @appointment = current_user.appointments.build
  end

  def create
    @appointment = Appointment.new(appointment_params.merge(user_id: current_user.id)) #instantiate an appointment associated with user, but unsaved
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else #reset user association on failed appointment save, set @appointments to disclude unpersisted appointment for partial
      @appointment.user = nil
      @appointments = current_user.appointments.select { |appt| appt.persisted? }
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      flash[:notice] = "Successfully updated appointment!"
      redirect_to appointment_path(@appointment)
    else
      @appointment.user = nil
      @appointments = current_user.appointments.select { |appt| appt.persisted? }
      render :edit
    end
  end

  def destroy
    @appointment.delete
    flash[:notice] = "Successfully deleted appointment!"
    redirect_to appointments_path
  end

  def list
    respond_to do |f|
      f.json { render json: current_user.appointments }
    end
  end


  private
  def set_appointments
    @appointments = current_user.appointments.all
  end

  def set_appointment
    @appointment = current_user.appointments.find_by(id: params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:name, :description, :contact_id, :location_id, :start_time, :contact_attributes => [:name, :email, :phone_number], :location_attributes => [:name])
  end

  def evaluate_params
    if params[:location_id]
      if current_user.locations.find_by(id: params[:location_id])
        @appointments = current_user.locations.find_by(id: params[:location_id]).list_upcoming_appointments
        render "appointments_without_calendar"
      else
        redirect_to appointments_path
      end
    elsif params[:contact_id]
      if current_user.contacts.find_by(id: params[:contact_id])
        @appointments = current_user.contacts.find_by(id: params[:contact_id]).list_upcoming_appointments
        render "appointments_without_calendar"
      else
        redirect_to appointments_path
      end
    elsif params[:week]
      render "simple_calendar/_weekly_calendar_appointments", locals: {appointments: @appointments}
    elsif params[:list]
      @appointments = current_user.list_upcoming_appointments
      render "appointments_without_calendar"
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

  def appt_start_time(appointment)
    appointment.start_time.strftime("%A, %b %e, at %l:%M %p")
  end

  def show_weekly_calendar(appointments)
      render partial: "simple_calendar/weekly_calendar_appointments", locals: {appointments: appointments}
   end

   def show_contact_fields
   end 

end

app/views/appointments/_appointment.html.erb
<div class="boxed">
  <fieldset>
    <legend><%= appointment.name %></legend>
  </fieldset>

  <p><strong>Description</strong>: <%= appointment.description %></p>
  <p><strong>Start Time</strong>: <%= appt_start_time(appointment) %></p>
  <p><strong>Contact</strong>: <% if has_complete_fields?(appointment.contact) %>
      <%= link_to appointment.contact.name, contact_path(appointment.contact) %> | <%= appointment.contact.email %> | <%= appointment.contact.phone_number %></p>
  <% else %>
     <%= "Incomplete contact information. Please update with 'Edit'!" %></p>
  <% end %>
  <p><strong>Location</strong>: <%= link_to appointment.location.name, location_path(appointment.location) %></p>

  <%= link_to "Edit", edit_appointment_path(appointment) %> | <%= link_to "Delete", @appointment, method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %> | <%= link_to "Back", appointments_path %>
  <br />
</div>

app/views/appointments/_contact_fields.html.erb
<tr>
  <td><%= g.label :name %></td>
  <td class="left"><%= g.text_field :name, :placeholder=> "Contact name" %> </td>
</tr>
<tr>
  <td><%= g.label :email %></td>
  <td class="left"><%= g.text_field :email, :placeholder=> "Contact email" %> </td>
</tr>
<tr>
  <td><%= g.label :phone_number, "Phone" %></td>
  <td class="left"><%= g.text_field :phone_number, :placeholder=> "Phone Number" %> </td>
</tr>

app/views/appointments/_error_fields.html.erb
<% if appointment.errors.any? %>
  <div id="error_explanation">
    <h4>There were some errors:</h4>
    <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/appointments/_existing_fields.html.erb
<% if current_user.contacts.any? %>
  <tr>
    <td><strong>Contact</strong></td>
    <td class="left"><%= f.collection_select :contact_id, current_user.contacts, :id, :name, :include_blank => true %></td>
  </tr>
<% end %>

<% if current_user.locations.any? %>
  <tr>
    <td><strong>Location</strong></td>
    <td class="left"><%= f.collection_select :location_id, current_user.locations, :id, :name, :include_blank => true %></td>
  </tr>
<% end %>

app/views/appointments/_form.html.erb
<%= render partial: "error_fields", locals: {appointment: appointment} %>

<%= form_for appointment do |f| %>
<table>
  <tr>
    <td><%= f.label :name %></td>
    <td class="left"><%= f.text_field :name, :placeholder=>"Name" %></td>
  </tr>
  <tr>
    <td><%= f.label :description %></td>
    <td class="left"><%= f.text_area :description, :placeholder=>"Description" %> </td>
  </tr>
  <tr>
    <td><%= f.label :start_time %></td>
    <td class="left"><%= f.datetime_local_field :start_time %> </td>
  </tr>

  <%= render partial: "existing_fields", locals: {f: f} %>
    <td></td>

    <tr>
      <td><legend></legend></td>
      <td class="left">Create a new Contact for this appointment: </td>
    </tr>
    <%= f.fields_for :contact, Contact.new do |g| %>
      <%= render partial: "contact_fields", locals: {g: g} %>
    <% end %>
    <td></td>

  <tr>
    <td><legend></legend></td>
    <td class="left">Create a new Location for this appointment: </td>
  </tr>
    <%= f.fields_for :location, Location.new do |g| %>
      <%= render partial: "location_fields", locals: {g: g} %>
    <% end %>
    <td></td>

  <tr>
    <td></td>
    <td class="left"><%= f.submit %></td>
  </tr>
</table>
<% end %>

app/views/appointments/_location_fields.html.erb
<tr>
  <td><%= g.label :name %></td>
  <td class="left"><%= g.text_field :name, :placeholder=>"Location Name" %> </td>
</tr>

app/views/appointments/appointments_without_calendar.html.erb
<fieldset>
  <legend>Appointments Index</legend>
</fieldset>

<% if @appointments.length == 1 %>
<h4 class="notice">You have <%=@appointments.length%> upcoming appointment.</h4><br/>
<% elsif @appointments.length > 1 %>
<h4 class="notice">You have <%=@appointments.length%> upcoming appointments.</h4><br/>
<% else %>
No appointments were found! <br /><br />
<% end %>

<% if @appointments.length > 0 %>
<button type="button" id="list_appointments" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
  List Appointments
</button>
<% else %>
<%= link_to "Click here to create an appointment.", new_appointment_path %>
<% end %>

<div id="appointments_list"><div>
<!-- <%= render(@appointments) || "No appointments were found!" %> -->

app/views/appointments/edit.html.erb
<div class="row">
    <div class="col-md-4">

      <fieldset>
        <legend>Edit this appointment!</legend>
      </fieldset>

        <%= render partial: 'appointments/form', locals: {appointment: @appointment} %><br />

      <p class="delete_button"><%= link_to "Delete this Appointment", @appointment, method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %> </p>
    </div>

  <div class="col-md-8">
    <%= show_weekly_calendar(@appointments) %>
  </div>

</div>

app/views/appointments/index.html.erb
<%= render partial: 'simple_calendar/monthly_calendar_appointments', locals: {appointments: @appointments} %>

app/views/appointments/new.html.erb
<div class="row">
    <div class="col-md-4">

      <fieldset>
        <legend>Create a New Appointment!</legend>
      </fieldset>

        <%= render partial: 'appointments/form', locals: {appointment: @appointment} %>
    </div>

  <div class="col-md-8">
    <%= show_weekly_calendar(@appointments) %>
  </div>

</div>

app/views/appointments/show.html.erb
<% if @appointment %>
<%= render partial: 'appointment', locals: {appointment: @appointment} %>
<% else %>
No such appointment was found!
<% end %>