config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :appointments, only: [:index]
  end

  resources :contacts do
    resources :appointments, only: [:index]
  end

  resources :appointments
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'welcome#home'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/list', to: 'appointments#list'
  get '/contacts/:id/get', to: 'contacts#get'
  get '/locations/:id/getAppointmentData', to: 'locations#getAppointmentData'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  include Appointable
  validates :name, presence: true
  validates :zip_code, format: { with: %r{\d{5}(-\d{4})?} }, allow_blank: true
  before_save :nil_if_blank

  belongs_to :user
  has_many :appointments, dependent: :destroy

  scope :search, lambda {|search| where(["name LIKE ?", "%#{search}%"])}

  private
    def nil_if_blank #convert blank columns to nil for view helpers
      attributes.each do |column, value|
        self[column].present? || self[column] = nil
      end
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = current_user.locations
    if !params[:location].blank?
      @locations = current_user.locations.search(params[:location])
    end
  end

  def new
    @location = current_user.locations.build
  end

  def create
    @location = Location.new(location_params.merge(user_id: current_user.id)) #instantiate a location associated with current_user, but unsaved
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      render :edit #add field with errors here
    end
  end

  def destroy
    @location.delete
    flash[:notice] = "Successfully deleted location."
    redirect_to locations_path
  end

  def getAppointmentData
    respond_to do |f|
      f.json { render json: current_user.locations.find_by_id(params[:id]).appointments }
    end
  end


  private
  def set_location
    @location = current_user.locations.find_by(id: params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :state, :city, :zip_code, :street_address)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper

  def has_empty_fields?(location)
    location.street_address == nil || location.zip_code == nil|| location.city == nil || location.state == nil
  end


end

app/views/locations/_form.html.erb
<% if location.errors.any? %>
  <div id="error_explanation">
    <h4>There were some errors:</h4>
    <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<%end%>

  <%= form_for location do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td> <%= f.text_field :name, :placeholder=>"Name" %> </td>
    </tr>
    <tr>
      <td><%= f.label :street_address %></td>
      <td><%= f.text_field :street_address, :placeholder=>"Street Address" %></td>
    </tr>
    <tr>
      <td><%= f.label :city %></td>
      <td><%= f.text_field :city, :placeholder=>"City" %></td>
    </tr>
    <tr>
      <td><%= f.label :state %></td>
      <td><%= f.text_field :state, :placeholder=>"State" %></td>
    </tr>
    <tr>
      <td><%= f.label :zip_code %></td>
      <td><%= f.text_field :zip_code, :placeholder=>"Zip Code" %></td>
    </tr>
    <tr>
      <td></td>
      <td class="left"><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/locations/_location.html.erb
<div class="boxed">
<fieldset>
  <legend><%= location.name %></legend>
</fieldset>

  <% if location.has_upcoming_appointments? %>
    <button type="button" id="showModal" class="btn btn-primary" data-toggle="modal" data-id="<%=location.id%>" data-target="#appointmentModal">View Appointments For This Location</button> <br /><br />
  <% end %>

  <% if has_empty_fields?(location) %>
    <p>This location has incomplete data! Update it by selecting 'Edit'.</p>
  <% else %>
    <p><%= location.street_address %></p>
    <p><%= location.city %>, <%= location.state %>, <%= location.zip_code %></p>
  <% end %>
  <p><%= link_to "Edit", edit_location_path(location) %> | <%= link_to "Delete", location_path(location), method: :delete, data: { confirm: "Are you sure you want to delete this location?" } %></p>

  <div class="modal fade" id="appointmentModal" tabindex="-1" role="dialog" data-id="<%=location.id%>" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="exampleModalLabel"><strong>Appointments for <%= location.name %></strong></h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <ul class="modal-body">
          </ul>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/locations/edit.html.erb
<fieldset>
  <legend>Edit <%= @location.name %></legend>
</fieldset>

<%= render partial: 'form', locals: {location: @location} %>

app/views/locations/index.html.erb
<fieldset>
  <legend>Locations Index</legend>
</fieldset>

<div>
  <h4>Search By Name:</h4>
  <%= form_tag("/locations", method: :get) do %>
    <%= text_field_tag "location" %>
    <%= submit_tag "Search" %>
    <% end %>
  </div> <br />

<%= render(@locations) || "You haven't saved any locations yet!" %>

app/views/locations/new.html.erb
<fieldset>
  <legend>Save a New Location</legend>
</fieldset>

<%= render partial: 'locations/form', locals: {location: @location} %>

app/views/locations/show.html.erb
<% if @location %>
<%= render partial: 'location', locals: {location: @location} %>
<% else %>
<p>No such location was found!</p>
<% end %>