config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :appointments, only: [:index]
  end

  resources :contacts do
    resources :appointments, only: [:index]
  end

  resources :appointments
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'welcome#home'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/list', to: 'appointments#list'
  get '/contacts/:id/get', to: 'contacts#get'
  get '/locations/:id/getAppointmentData', to: 'locations#getAppointmentData'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<h4><%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %></h4>
<h4><%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %></h4>
<h4><%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %></h4>
<br />

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer content">
      <p class="text-muted">&copy 2017 mdjurdj1 - Appointment Manager</p>
    </div>
</footer>

app/views/layouts/_login.html.erb
<%= form_for @user, method: "post", url: user_session_path do |f| %>
<%= f.text_field :email, :placeholder=>"Email Address" %> <br /> <br />
<%= f.password_field :password, :placeholder=>"Password" %> <br /> <br />
<%= f.submit "Sign In" %> <br /> <br />
<% end %>
<%= link_to "New Here? Join us!", new_user_registration_path %>
<%= link_to("Or, login with facebook!", "/auth/facebook") %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" id="navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Appointment Manager</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Appointments <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="dropdown_nav">
            <li><%= link_to "View this Month", appointments_path %>
            <li><%= link_to "View this Week", appointments_path(:week=>"week") %></li>
            <li><%= link_to "Create Appointment", new_appointment_path %></a></li>
            <li class="divider"></li>
            <li><%= link_to "List Upcoming Appointments", appointments_path(:list=>"list") %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Contacts <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="dropdown_nav">
            <li><%= link_to "View all Contacts", contacts_path %>
            <li><%= link_to "Create new Contact", new_contact_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Locations <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="dropdown_nav">
            <li><%= link_to "View all Locations", locations_path %>
            <li><%= link_to "Create new Location", new_location_path %></li>
          </ul>
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <p class="navbar-text" id="Signout_link"><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></p>
        <% else %>
          <p class="navbar-text" id="Login_link"><%= link_to "Log In", new_user_session_path %></p>
			</ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointment Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
  </head>

  <body class="<%= body_class %>">
      <%= render 'layouts/navbar' %>
      <div class="main container">
        <%= render 'layouts/errors' unless current_page = root_path %>
        <%= yield %>
      </div><!--/container-->
    <%= render 'layouts/footer' %>

  </body>

</html>